sudo: required
services:
  - docker
before_install:
  - docker pull yglukhov/debian-stretch.base.nim
script:
  - docker run -v "$(pwd):/project" -w /project yglukhov/debian-stretch.base.nim nim --version
  - docker run -v "$(pwd):/project" -w /project yglukhov/debian-stretch.base.nim nimble test
